keys:
  - &tguimbert 84C6034EC4BA4925!
  - &leshen age1z9sg234z37jz5gcudesqvxyq6cfxag6c3t9ws65edc9zevhlguwqz6dttq
  - &wyvern age1rds0gutzcrn45zl4ryvyn4hkmqf9p287mhzrmm2ye2fvflfvpczqtkr55a
  - &griffin age1yqhanjmtqc20slmmdqprx7h9nm6j2hhzsnxg6v23dnfasp4c7phq6gkk96
  - &tuxedo age18py95mm2elyuku37rr72k4z8zeeffckug45wv0h6kxncf52eg5rsx0gwsa
creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - pgp:
          - *tguimbert
        age:
          - *leshen
          - *wyvern
          - *griffin
          - *tuxedo
  - path_regex: secrets/leshen/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *tguimbert
        age:
          - *leshen
