keys:
  - &tguimbert 84C6034EC4BA4925!
  - &leshen age1z9sg234z37jz5gcudesqvxyq6cfxag6c3t9ws65edc9zevhlguwqz6dttq
  - &griffin age1yqhanjmtqc20slmmdqprx7h9nm6j2hhzsnxg6v23dnfasp4c7phq6gkk96
  - &tuxedo age18py95mm2elyuku37rr72k4z8zeeffckug45wv0h6kxncf52eg5rsx0gwsa
  - &srv-01 age1fw5kc4cggy0al3j6l85k8sk3r8xxfz4tgwt58w6yfx4g47w674msra78sv
creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - pgp:
          - *tguimbert
        age:
          - *leshen
          - *griffin
          - *tuxedo
  - path_regex: secrets/leshen/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *tguimbert
        age:
          - *leshen
  - path_regex: secrets/srv-01.yaml$
    key_groups:
      - pgp:
          - *tguimbert
        age:
          - *srv-01
