keys:
  - &tguimbert 84C6034EC4BA4925!
  - &leshen age1z9sg234z37jz5gcudesqvxyq6cfxag6c3t9ws65edc9zevhlguwqz6dttq
creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - pgp:
          - *tguimbert
        age:
          - *leshen
  - path_regex: secrets/leshen/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *tguimbert
        age:
          - *leshen
