name: "Cachix"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
        skipPush: true
    - uses: cachix/cachix-action@v12
      with:
        name: tguimbert
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build NixOs configuration
      run: nix build .#nixosConfigurations.griffin.config.system.build.toplevel
    # - name: Build Home-Manager configuration
    #   run: nix build .#homeConfigurations."tguimbert@griffin".activationPackage
    - name: Build DevShell configuration
      run: nix develop --build
