name: "Cachix"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-hosts:
    strategy:
      matrix:
        host: [ griffin, leshen ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
        skipPush: true
    - uses: cachix/cachix-action@v12
      with:
        name: tguimbert
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build NixOs configuration
      run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

  build-devshell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
        skipPush: true
    - uses: cachix/cachix-action@v12
      with:
        name: tguimbert
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build DevShell configuration
      run: nix develop --build --impure
