name: "Cachix"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cache-overlays:
    name: Cache Overlays
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Add personal cachix configuration
        uses: cachix/cachix-action@v13
        with:
          name: tguimbert
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build overlay packages
        working-directory: overlays
        run: |
          for dir in *; do
            nix build .#pkgs.x86_64-linux.nixpkgs."$dir"
          done;
          
