name: "Cachix"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-derivations:
    strategy:
      matrix:
        derivation: 
          - nixosConfigurations.griffin.config.system.build.toplevel
          - nixosConfigurations.leshen.config.system.build.toplevel
          # - devShells.x86_64-linux.default
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
        skipPush: true
    - uses: cachix/cachix-action@v12
      with:
        name: tguimbert
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build NixOs configuration
      run: |
        nix run github:Mic92/nix-fast-build -- \
        --flake .#${{ matrix.derivation }} \
        --skip-cached \
        --no-nom
